name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Updated to v3 for latest compatibility

      - name: Setup Node
        uses: actions/setup-node@v3  # Updated to v3 for Node.js compatibility
        with:
          node-version: 20  # Use Node 20 for compatibility with future updates

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4  # Updated to v4 as v3 is deprecated
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Use v3 in deploy job as well

      - name: Download artifact
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Check for the latest version or use v3 if v4 isn't available
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
